package au.com.marlo.students.tdourado.xml.jaxb.model.response;

import au.com.marlo.students.tdourado.xml.jaxb.model.order.Order;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * The following classes were automatically generated using JAXB. However, these models have been
 * altered to better fit the schema's original definitions.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "response",
    propOrder = {"orders"})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@XmlRootElement
public class Response {

  @XmlElement(required = true)
  protected Response.Orders orders;

  /**
   * Orders class represented inside Response due to import of another namespace. This was
   * auto-generated by JAXB. Attempting to change and remodel it to use just a list of Orders
   * results in a mismatch in the expected XML structure and the result. This is a temporary
   * solution to properly fit the schema definition.
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"order"})
  @Getter
  @Setter
  @NoArgsConstructor
  @AllArgsConstructor
  @ToString
  public static class Orders {
    @XmlElement(namespace = "http://www.marlo.com.au/training/order")
    protected List<Order> order;
  }
}
